export const All_RESTAURANT_REQUEST = "All_RESTAURANT_REQUEST";
export const All_RESTAURANT_SUCCESS = "All_RESTAURANT_SUCCESS";
export const All_RESTAURANT_FAIL = "All_RESTAURANT_FAIL";

export const RESTAURANT_DETAILS_REQUEST = "RESTAURANT_DETAILS_REQUEST";
export const RESTAURANT_DETAILS_SUCCESS = "RESTAURANT_DETAILS_SUCCESS";
export const RESTAURANT_DETAILS_FAIL = "RESTAURANT_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";